### ISSUE TITLE
SNR plotting for phantom data fails

### ISSUE THREAD

**Issue by ktavabi** [BioMag/meg_scripts#3]
`python` [chpi_snr.py chpi_snr_test_raw.fif](https://www.dropbox.com/s/edkw8jguo8syzrt/chpi_snr_test_raw.fif?dl=0) `--stop 500` results in `ValueError`:

> Traceback (most recent call last):
>   File "chpi_snr.py", line 87, in <module>
>     coeffs = np.dot(inv_model, megbuf)
> ValueError: shapes (18,2000) and (1000,306) not aligned: 2000 (dim 1) != 1000 (dim 0)

**Comment by jjnurminen** [comment]
I get the following:

```
Range : 30000 ... 228999 =     30.000 ...   228.999 secs
[...]
Traceback (most recent call last):
  File "python/chpi_snr.py", line 86, in <module>
    megbuf = raw[pick_meg, buf0:buf0+buflen][0].transpose()
  File "/home/jussi/projects/mne-python/mne/io/base.py", line 758, in __getitem__
    verbose=self.verbose)
  File "/home/jussi/projects/mne-python/mne/io/base.py", line 404, in _read_segment
    raise ValueError('No data in this range')
ValueError: No data in this range
```

So it looks like there is only ~200 seconds of data. Maybe due to different mne version, it causes a short buffer read for you when specifying `--stop=500`. Then the inverse model will not match the MEG data buffer anymore. Try if it works without the stop argument.

By the way, are you aware that chpi_snr is already in the i-LABS mnefun repository? I would recommend using that version, since it has many fixes/enhancements that are not in this repo.

**Comment by ktavabi** [comment]
@jjnurminen Thanks It works without/appropriate `--stop` arg. Also I started using the function as in mnefun see [here](https://github.com/LABSN/mnefun/pull/151)
